basePath: /
consumes:
- application/json
- application/xml
definitions:
  WalletResponse:
    description: WalletResponse wallet response struct for http apis
    properties:
      entries:
        items:
          $ref: '#/definitions/walletEntry'
        type: array
        x-go-name: Entries
      meta:
        $ref: '#/definitions/walletMeta'
    type: object
    x-go-package: github.com/skycoin/skycoin/src/api
  walletEntry:
    description: WalletEntry the wallet entry struct
    properties:
      address:
        type: string
        x-go-name: Address
      public_key:
        type: string
        x-go-name: Public
    type: object
    x-go-name: WalletEntry
    x-go-package: github.com/skycoin/skycoin/src/readable
  walletMeta:
    description: WalletMeta the wallet meta struct
    properties:
      coin:
        type: string
        x-go-name: Coin
      crypto_type:
        type: string
        x-go-name: CryptoType
      encrypted:
        type: boolean
        x-go-name: Encrypted
      filename:
        type: string
        x-go-name: Filename
      label:
        type: string
        x-go-name: Label
      timestamp:
        format: int64
        type: integer
        x-go-name: Timestamp
      type:
        type: string
        x-go-name: Type
      version:
        type: string
        x-go-name: Version
    type: object
    x-go-name: WalletMeta
    x-go-package: github.com/skycoin/skycoin/src/readable
host: staging.node.skycoin.net
info:
  contact:
    email: skycoin.doe@example.com
    name: Skycoin project
    url: https://www.skycoin.net
  description: Skycoin is a next-generation cryptocurrency.
  title: Skycoin REST API.
  version: 0.25.0
paths:
  /api/v1/address/verify:
    post:
      operationId: verifyAddressRequest
      parameters:
      - in: body
        name: address
        required: true
        schema:
          type: string
        x-go-name: Address
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/verifyAddressResponse'
        default:
          $ref: '#/responses/genericError'
      schemes:
      - http
      - https
      security:
      - csrfAuth:
        - '[]'
      summary: healthHandler returns node health data.
      tags:
      - verify_address
  /api/v1/coinSupply:
    get:
      description: coinSupplyHandler returns coin distribution supply stats
      operationId: coinSupply
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/coinSupply'
        "422":
          $ref: '#/responses/validationError'
        default:
          $ref: '#/responses/genericError'
      schemes:
      - http
      - https
      security:
      - csrfAuth:
        - '[]'
  /api/v1/csrf:
    get:
      operationId: csrf
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/csrfResponse'
        default:
          $ref: '#/responses/genericError'
      schemes:
      - http
      - https
      security:
      - csrfAuth:
        - '[]'
      summary: Creates a new CSRF token. Previous CSRF tokens are invalidated by this
        call.
  /api/v1/network/defaultConnections:
    get:
      operationId: defaultConnections
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/defaultConnectionsResponse'
        default:
          $ref: '#/responses/genericError'
      schemes:
      - http
      - https
      security:
      - csrfAuth:
        - '[]'
      summary: defaultConnectionsHandler returns the list of default hardcoded bootstrap
        addresses.\n They are not necessarily connected to.
  /api/v1/resendUnconfirmedTxns:
    post:
      consumes:
      - application/json
      description: Broadcasts all unconfirmed transactions from the unconfirmed transaction
        pool
      operationId: resendUnconfirmedTxns
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/resendResult'
        default:
          $ref: '#/responses/genericError'
      schemes:
      - http
      - https
      security:
      - csrfAuth:
        - '[]'
  /api/v1/version:
    get:
      description: versionHandler returns the application version info
      operationId: version
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/buildInfo'
        default:
          $ref: '#/responses/genericError'
      schemes:
      - http
      - https
      security:
      - csrfAuth:
        - '[]'
  /api/v1/wallets:
    get:
      description: Generates new addresses
      operationId: wallets
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/walletsResponse'
        default:
          $ref: '#/responses/genericError'
      schemes:
      - http
      - https
      security:
      - csrfAuth:
        - '[]'
  /api/v1/wallets/folderName:
    get:
      description: Returns the wallet directory path
      operationId: walletFolder
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/walletFolderResponse'
        default:
          $ref: '#/responses/genericError'
      schemes:
      - http
      - https
      security:
      - csrfAuth:
        - '[]'
    post:
      description: |-
        Consume:
        application/json
      operationId: walletParams
      parameters:
      - description: Parameters for Wallet New Address
        in: body
        name: Params
        schema:
          properties:
            id:
              type: string
              x-go-name: Id
            num:
              format: int64
              type: integer
              x-go-name: Num
            password:
              type: string
              x-go-name: Password
          required:
          - id
          type: object
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/walletAddressResponse'
        default:
          $ref: '#/responses/genericError'
      schemes:
      - http
      - https
      security:
      - csrfAuth:
        - '[]'
      summary: Generates new addresses
      tags:
      - walletNewAddresses
produces:
- application/json
- application/xml
responses:
  buildInfo:
    description: BuildInfo represents the build info
    headers:
      branch:
        description: git branch name
        type: string
      commit:
        description: git commit id
        type: string
      version:
        description: version number
        type: string
  coinSupply:
    description: CoinSupply records the coin supply info
    headers:
      current_coinhour_supply:
        description: CurrentCoinHourSupply is coins hours in non distribution addresses
        type: string
      current_supply:
        description: 'Coins distributed beyond the project:'
        type: string
      locked_distribution_addresses:
        description: Distribution addresses which are locked and do not count towards
          total supply
        items:
          type: string
        type: array
      max_supply:
        description: MaxSupply is the maximum number of coins to be distributed ever
        type: string
      total_coinhour_supply:
        description: TotalCoinHourSupply is coin hours in all addresses including
          unlocked distribution addresses
        type: string
      total_supply:
        description: TotalSupply is CurrentSupply plus coins held by the distribution
          addresses that are spendable
        type: string
      unlocked_distribution_addresses:
        description: Distribution addresses which count towards total supply
        items:
          type: string
        type: array
  csrfResponse:
    description: Response to address /api/v1/csrf.
    schema:
      properties:
        csrf_token:
          description: Body of csrf Token
          type: string
          x-go-name: Token
      type: object
  defaultConnectionsResponse:
    description: This struct is for endpoint /api/v1/defaultConnections response.
    headers:
      DefaultConnections:
        items:
          type: string
        type: array
  genericError:
    description: |-
      A GenericError is the default error message that is generated.
      For certain status codes there are more appropriate error structures.
    schema:
      properties:
        code:
          format: int32
          type: integer
          x-go-name: Code
        message:
          type: string
          x-go-name: Message
      type: object
  resendResult:
    description: ResendResult the result of rebroadcasting transaction
    headers:
      txids:
        items:
          type: string
        type: array
  validationError:
    description: |-
      A ValidationError is an that is generated for validation failures.
      It has the same fields as a generic error but adds a Field property.
    schema:
      properties:
        code:
          format: int32
          type: integer
          x-go-name: Code
        field:
          type: string
          x-go-name: Field
        message:
          type: string
          x-go-name: Message
      type: object
  verifyAddressResponse:
    description: VerifyAddressResponse is returned by POST /api/v2/address/verify
    headers:
      version:
        format: uint8
        type: integer
  walletAddressResponse:
    description: This struct is for catch wallet addresses
    headers:
      addresses:
        items:
          type: string
        type: array
  walletFolderResponse:
    description: WalletFolder struct
    headers:
      address:
        type: string
  walletsResponse:
    description: This struct is for endpoint /api/v1/wallets response
    schema:
      items:
        $ref: '#/definitions/WalletResponse'
      type: array
schemes:
- http
- https
security:
- csrfAuth:
  - '[]'
securityDefinitions:
  csrfAuth:
    in: header
    name: csrf_Token
    type: apiKey
swagger: "2.0"
